### PR TITLE
Add RHBA-2018:2654 details to release notes

### PR DESCRIPTION
**Pull request by tmorriso-rh**
To be released 2018-09-18

### CODE REVIEW

**Comment by tmorriso-rh** [comment]
@vikram-redhat Can you take a look at this PR? All of the changes are in the file, but it has a PR number of 1, which I am sure is incorrect.  @ahardin-rh Please hold off on reviewing until after Vikram has reviewed. Thanks.

**Comment by vikram-redhat** [comment]
@tmorriso-rh - Hi, this PR is in your repo, not the openshift-docs one.

**Comment by tmorriso-rh** [comment]
@vikram-redhat D'oh! OK, I will open a new one in the right repo and then close this one. Thanks.

**Comment by tmorriso-rh** [comment]
@vikram-redhat Can you ping me when you are online? I tried creating a new PR on master, but it seems to still create it in my repo and not the openshift-docs repo. Here is the link: https://github.com/tmorriso-rh/openshift-docs/pull/new/RHBA-2018-2654-update

Please advise. Thanks.

**Comment by vikram-redhat** [comment]
@tmorriso-rh - not sure what is happening here, but it might be best to create a new branch for these changes and start again.

**Comment by tmorriso-rh** [comment]
> @tmorriso-rh - not sure what is happening here, but it might be best to create a new branch for these changes and start again.

Yes, I tried that, and it still tried to create the PR from my repo. Can you walk me thru how to do a reset?

**Comment by tmorriso-rh** [comment]
Closing in favor of https://github.com/openshift/openshift-docs/pull/12014.

**Pull request closed without merging**
